In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\ankur\\Documents\\Data Science\\Projects\\EBS\\Beginner Python Pandas 101\\examples\\ex1.csv")
df = pd.read_csv("examples\ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [7]:
df.iloc[2,:]

a            9
b           10
c           11
d           12
message    foo
Name: 2, dtype: object

In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
df.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
df["a"]

0    1
1    5
2    9
Name: a, dtype: int64

In [2]:
df.message

0    hello
1    world
2      foo
Name: message, dtype: object

In [3]:
start = df.message.str.startswith('w')
end = df.message.str.endswith('o')
print(start)
print(end)

0    False
1     True
2    False
Name: message, dtype: bool
0     True
1    False
2     True
Name: message, dtype: bool

In [4]:
s = df[start]
s

   a  b  c  d message
1  5  6  7  8   world

In [5]:
e = df[end]
e

   a   b   c   d message
0  1   2   3   4   hello
2  9  10  11  12     foo

In [6]:
pd.concat([df[start], df[end]])

   a   b   c   d message
1  5   6   7   8   world
0  1   2   3   4   hello
2  9  10  11  12     foo

In [7]:
df.sort_values("message")

   a   b   c   d message
2  9  10  11  12     foo
0  1   2   3   4   hello
1  5   6   7   8   world

In [8]:
df.sort_values("a", ascending=True)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
df = pd.DataFrame({'angles': [0, 3, 4],
                    'degrees': [360, 180, 360]},
                   index=['circle', 'triangle', 'rectangle'])
df

           angles  degrees
circle          0      360
triangle        3      180
rectangle       4      360

In [11]:
df1 = df.copy()
for i23tt in range(len(df)):
    df1.degrees[i23tt] = df.degrees[i23tt] * 2
df1

           angles  degrees
circle          0      720
triangle        3      360
rectangle       4      720

In [12]:
# len is row
len(df)

3

In [13]:
range(5)

range(0, 5)

In [14]:
df2 = pd.DataFrame({'angles': [100, 300, 400],
                    'degrees': [36000, 18000, 36000]},
                   index=['circle', 'triangle', 'rectangle'])
df2

           angles  degrees
circle        100    36000
triangle      300    18000
rectangle     400    36000

In [15]:
df + df2

           angles  degrees
circle        100    36360
triangle      303    18180
rectangle     404    36360

In [49]:
import pandas as pd

In [53]:
file = "Sample 111419.xlsx"
df = pd.read_excel(file)

In [78]:
df

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,weight,Cg Weight,Freight Charge,Total Revenue,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year
0,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,15.64,21.68,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
1,DMH000054437,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,17.23,20.59,2019-01-07,2019-01-08,15:19:00,SONY - 9807237,A1512066,2019
2,DMH000054592,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,12.95,18.46,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
3,DMH000054593,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,32,55,28.52,34.08,2019-01-14,2019-01-11,08:43:00,SONY - 9807237,A1514438,2019
4,DMH000054701,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,22.04,29.33,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
5,DMH000054702,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,13,22.04,29.33,2019-01-09,2019-01-08,12:24:00,SONY - 9807237,A1514438,2019
6,DMH000054703,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,9,9,20.13,27.04,2019-01-09,2019-01-11,17:12:00,SONY - 9807237,A1514438,2019
7,DMH000054704,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,9,18.33,24.89,2019-01-09,2019-01-09,13:11:00,SONY - 9807237,A1514438,2019
8,DMH000054815,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,19.42,25.54,2019-01-11,2019-01-14,08:45:00,SONY - 9807237,A1514438,2019
9,DMH000054817,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,14.62,17.03,2019-01-15,2019-01-14,13:22:00,SONY - 9807237,A1514438,2019
10,DMH000054825,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,16.58,22.23,2019-01-10,2019-01-12,11:24:00,SONY - 9807237,A1514438,2019
11,DMH000054827,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,8,14.62,19.94,2019-01-15,2019-01-14,10:29:00,SONY - 9807237,A1514438,2019
12,DMH000054759,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,50,58,69.95,81.49,2019-01-10,2019-01-10,10:29:00,SONY - 9807237,A1514438,2019
13,DMH000054762,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,118,128,51.02,85.46,2019-01-15,2019-01-14,09:24:00,SONY - 9807237,A1514438,2019
14,DMH000054889,2019-01-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,8,17.44,23.23,2019-01-11,2019-01-11,15:34:00,SONY - 9807237,A1514438,2019
15,DMH000054892,2019-01-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,10,10,19.23,25.32,2019-01-11,2019-01-17,10:22:00,SONY - 9807237,A1514438,2019
16,DMH000055001,2019-01-09,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,9,20.13,26.36,2019-01-14,2019-01-14,14:44:00,SONY - 9807237,A1514438,2019
17,DMH000055002,2019-01-09,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,85,85,37.76,43.99,2019-01-17,2019-01-15,10:58:00,SONY - 9807237,A1514438,2019
18,DMH000057262,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,17.08,22.61,2019-02-13,2019-02-14,11:37:00,SONY - 9807237,A1518983,2019
19,DMH000057265,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,17.08,22.61,2019-02-13,2019-02-12,13:07:00,SONY - 9807237,A1518983,2019
20,DMH000057266,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,20,21,30.68,38.32,2019-02-13,2019-02-21,20:50:00,SONY - 9807237,A1518983,2019
21,DMH000057267,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,20,21,30.68,38.32,2019-02-13,2019-02-15,13:43:00,SONY - 9807237,A1518983,2019
22,DMH000057269,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,17.08,22.61,2019-02-13,2019-02-14,13:49:00,SONY - 9807237,A1518983,2019
23,DMH000057153,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,18,18,17.61,20.34,2019-02-19,2019-02-15,10:10:00,SONY - 9807237,A1518983,2019
24,DMH000057155,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,2,15.06,17.39,2019-02-18,2019-02-15,11:44:00,SONY - 9807237,A1518983,2019
25,DMH000057156,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,161,170,66.14,92.26,2019-02-19,2019-02-15,11:56:00,SONY - 9807237,A1518983,2019
26,DMH000057166,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,42,43,54.48,62.92,2019-02-13,2019-02-13,08:25:00,SONY - 9807237,A1518983,2019
27,DMH000057169,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,57,58,72.05,83.22,2019-02-13,2019-02-13,08:58:00,SONY - 9807237,A1518983,2019
28,DMH000057170,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,23,24,33.63,38.84,2019-02-13,2019-02-12,10:12:00,SONY - 9807237,A1518983,2019
29,DMH000056956,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,100,106,46.02,61.43,2019-02-19,2019-02-15,08:34:00,SONY - 9807237,A1518983,2019
30,DMH000056958,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,83,113,47.80,78.15,2019-02-19,2019-02-15,09:28:00,SONY - 9807237,A1518983,2019
31,DMH000056977,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,80,79,36.99,49.38,2019-02-19,2019-02-15,13:05:00,SONY - 9807237,A1518983,2019
32,DMH000056987,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,15.06,20.28,2019-02-19,2019-02-15,11:48:00,SONY - 9807237,A1518983,2019
33,DMH000059296,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,6,16.11,21.49,2019-03-20,2019-03-19,11:49:00,SONY - 9807237,A1524874,2019
34,DMH000059298,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,10,10,15.06,17.39,2019-03-25,2019-03-22,08:32:00,SONY - 9807237,A1524874,2019
35,DMH000059299,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,14,15,24.64,31.35,2019-03-20,2019-03-20,08:57:00,SONY - 9807237,A1524874,2019
36,DMH000059301,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,10,10,15.06,17.39,2019-03-25,2019-03-22,09:00:00,SONY - 9807237,A1524874,2019
37,DMH000059737,2019-03-22,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,16.11,21.49,2019-03-27,2019-03-26,13:23:00,SONY - 9807237,A1525978,2019
38,DMH000059739,2019-03-22,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,16.11,21.49,2019-03-27,NaT,NaN,SONY - 9807237,A1525978,2019
39,DMH000059798,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,9,9,18.88,21.81,2019-03-28,2019-04-01,14:47:00,SONY - 9807237,A1525978,2019
40,DMH000059749,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,16.11,21.49,2019-03-28,2019-03-28,14:51:00,SONY - 9807237,A1525978,2019
41,DMH000059750,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,1,6,18.98,24.81,2019-03-28,2019-03-28,16:20:00,SONY - 9807237,A1525978,2019
42,DMH000059751,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,16.11,21.49,2019-03-28,2019-03-28,14:51:00,SONY - 9807237,A1525978,2019
43,DMH000059753,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,8,17.96,23.63,2019-03-28,2019-04-01,17:35:00,SONY - 9807237,A1525978,2019
44,DMH000067885,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,14,12,21.76,27.90,2019-08-07,2019-08-07,11:38:00,SONY - 9807237,A1547385,2019
45,DMH000067886,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,13,11,20.78,26.72,2019-08-07,2019-08-07,12:14:00,SONY - 9807237,A1547385,2019
46,DMH000067888,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,11,9,18.88,22.66,2019-08-07,2019-08-07,13:33:00,SONY - 9807237,A1547385,2019
47,DMH000067908,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,2,15.06,18.15,2019-08-14,2019-08-09,12:31:00,SONY - 9807237,A1547385,2019
48,DMH000067909,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,114,110,132.42,159.57,2019-08-09,2019-08-09,11:48:00,SONY - 9807237,A1547385,2019
49,DMH000067912,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,10,11,15.39,18.54,2019-08-14,2019-08-14,08:26:00,SONY - 9807237,A1547385,2019

In [107]:
df1 = df.copy()
df11 = df1[["HWB", "HWB Date", "Orig City", "Orig zip", "Shipper State"]]
df12 = df1[["HWB", "weight", "Cg Weight", "Freight Charge", "Total Revenue"]]

In [56]:
df_group = df.groupby("HWB Date").agg('count')
df_group["HWB"]

HWB Date
2019-01-02     2
2019-01-04     6
2019-01-07     6
2019-01-08     2
2019-01-09     2
2019-02-08    15
2019-03-15     4
2019-03-22     2
2019-03-25     5
2019-08-02     3
2019-08-06     3
Name: HWB, dtype: int64

In [57]:
df[["HWB Date","weight","Total Revenue"]].groupby("HWB Date").agg(['count','mean','sum'])

           weight                 Total Revenue
            count       mean  sum         count       mean     sum
HWB Date
2019-01-02      2   3.000000    6             2  21.135000   42.27
2019-01-04      6  11.333333   68             6  27.188333  163.13
2019-01-07      6  32.833333  197             6  41.948333  251.69
2019-01-08      2   8.500000   17             2  24.275000   48.55
2019-01-09      2  46.500000   93             2  35.175000   70.35
2019-02-08     15  42.333333  635            15  44.578667  668.68
2019-03-15      4   9.250000   37             4  21.905000   87.62
2019-03-22      2   3.000000    6             2  21.490000   42.98
2019-03-25      5   4.200000   21             5  22.646000  113.23
2019-08-02      3  12.666667   38             3  25.760000   77.28
2019-08-06      3  42.333333  127             3  65.420000  196.26

In [86]:
df[["HWB Date","weight","Total Revenue"]].groupby("HWB Date").agg(['count','mean','sum'])

           weight                 Total Revenue
            count       mean  sum         count       mean     sum
HWB Date
2019-01-02      2   3.000000    6             2  21.135000   42.27
2019-01-04      6  11.333333   68             6  27.188333  163.13
2019-01-07      6  32.833333  197             6  41.948333  251.69
2019-01-08      2   8.500000   17             2  24.275000   48.55
2019-01-09      2  46.500000   93             2  35.175000   70.35
2019-02-08     15  42.333333  635            15  44.578667  668.68
2019-03-15      4   9.250000   37             4  21.905000   87.62
2019-03-22      2   3.000000    6             2  21.490000   42.98
2019-03-25      5   4.200000   21             5  22.646000  113.23
2019-08-02      3  12.666667   38             3  25.760000   77.28
2019-08-06      3  42.333333  127             3  65.420000  196.26

In [72]:
count = df[["HWB Date","weight","Total Revenue"]].groupby("HWB Date").agg(['count','mean','sum']).iloc[:,0]
count

HWB Date
2019-01-02     2
2019-01-04     6
2019-01-07     6
2019-01-08     2
2019-01-09     2
2019-02-08    15
2019-03-15     4
2019-03-22     2
2019-03-25     5
2019-08-02     3
2019-08-06     3
Name: (weight, count), dtype: int64

In [73]:
wT = df[["HWB Date","weight","Total Revenue"]].groupby("HWB Date").agg(['mean','sum']).iloc[:,:]
wT

               weight      Total Revenue
                 mean  sum          mean     sum
HWB Date
2019-01-02   3.000000    6     21.135000   42.27
2019-01-04  11.333333   68     27.188333  163.13
2019-01-07  32.833333  197     41.948333  251.69
2019-01-08   8.500000   17     24.275000   48.55
2019-01-09  46.500000   93     35.175000   70.35
2019-02-08  42.333333  635     44.578667  668.68
2019-03-15   9.250000   37     21.905000   87.62
2019-03-22   3.000000    6     21.490000   42.98
2019-03-25   4.200000   21     22.646000  113.23
2019-08-02  12.666667   38     25.760000   77.28
2019-08-06  42.333333  127     65.420000  196.26

In [77]:
pd.merge(count, wT, on="HWB Date")

           weight                 Total Revenue
            count       mean  sum          mean     sum
HWB Date
2019-01-02      2   3.000000    6     21.135000   42.27
2019-01-04      6  11.333333   68     27.188333  163.13
2019-01-07      6  32.833333  197     41.948333  251.69
2019-01-08      2   8.500000   17     24.275000   48.55
2019-01-09      2  46.500000   93     35.175000   70.35
2019-02-08     15  42.333333  635     44.578667  668.68
2019-03-15      4   9.250000   37     21.905000   87.62
2019-03-22      2   3.000000    6     21.490000   42.98
2019-03-25      5   4.200000   21     22.646000  113.23
2019-08-02      3  12.666667   38     25.760000   77.28
2019-08-06      3  42.333333  127     65.420000  196.26

In [8]:
import pandas as pd
sampleA = pd.read_csv("sampleAnkur.csv")
sampleA.head()

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08

In [16]:
a = sampleA.iloc[:10,:]
b = sampleA.iloc[20:30,:]

import pandas as pd

pd.concat([a,b])

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
5,5,DMH000054702AC,2019-01-04,Express,4,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11
7,7,DMH000054704,2019-01-04,Express,8,9,24.89,2019-01-09,2019-01-09
8,8,DMH000054815,2019-01-07,Express,7,7,25.54,2019-01-11,2019-01-14
9,9,DMH000054817R1,2019-01-07,Ground,8,8,17.03,2019-01-15,2019-01-14
20,20,DMH000057266,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-21
21,21,DMH000057267,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-15
22,22,DMH000057269AC,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
23,23,DMH000057153,2019-02-08,Ground,18,18,20.34,2019-02-19,2019-02-15
24,24,DMH000057155,2019-02-08,Ground,2,2,17.39,2019-02-18,2019-02-15
25,25,DMH000057156,2019-02-08,Ground,161,170,92.26,2019-02-19,2019-02-15
26,26,DMH000057166,2019-02-08,Express,42,43,62.92,2019-02-13,2019-02-13
27,27,DMH000057169,2019-02-08,Express,57,58,83.22,2019-02-13,2019-02-13
28,28,DMH000057170,2019-02-08,Express,23,24,38.84,2019-02-13,2019-02-12
29,29,DMH000056956,2019-02-08,Ground,100,106,61.43,2019-02-19,2019-02-15

In [149]:
noR1AC = sampleA[(sampleA['HWB'].str.contains('R1') == False) &
       (sampleA['HWB'].str.contains('AC') == False)]
len(noR1AC)

43

In [5]:
sampleA

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
5,5,DMH000054702AC,2019-01-04,Express,4,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11
7,7,DMH000054704,2019-01-04,Express,8,9,24.89,2019-01-09,2019-01-09
8,8,DMH000054815,2019-01-07,Express,7,7,25.54,2019-01-11,2019-01-14
9,9,DMH000054817R1,2019-01-07,Ground,8,8,17.03,2019-01-15,2019-01-14
10,10,DMH000054825,2019-01-07,Express,7,7,22.23,2019-01-10,2019-01-12
11,11,DMH000054827R1,2019-01-07,Ground,7,8,19.94,2019-01-15,2019-01-14
12,12,DMH000054759,2019-01-07,Express,50,58,81.49,2019-01-10,2019-01-10
13,13,DMH000054762,2019-01-07,Ground,118,128,85.46,2019-01-15,2019-01-14
14,14,DMH000054889,2019-01-08,Express,7,8,23.23,2019-01-11,2019-01-11
15,15,DMH000054892,2019-01-08,Express,10,10,25.32,2019-01-11,2019-01-17
16,16,DMH000055001AC,2019-01-09,Express,8,9,26.36,2019-01-14,2019-01-14
17,17,DMH000055002,2019-01-09,Ground,85,85,43.99,2019-01-17,2019-01-15
18,18,DMH000057262,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
19,19,DMH000057265AC,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-12
20,20,DMH000057266,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-21
21,21,DMH000057267,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-15
22,22,DMH000057269AC,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
23,23,DMH000057153,2019-02-08,Ground,18,18,20.34,2019-02-19,2019-02-15
24,24,DMH000057155,2019-02-08,Ground,2,2,17.39,2019-02-18,2019-02-15
25,25,DMH000057156,2019-02-08,Ground,161,170,92.26,2019-02-19,2019-02-15
26,26,DMH000057166,2019-02-08,Express,42,43,62.92,2019-02-13,2019-02-13
27,27,DMH000057169,2019-02-08,Express,57,58,83.22,2019-02-13,2019-02-13
28,28,DMH000057170,2019-02-08,Express,23,24,38.84,2019-02-13,2019-02-12
29,29,DMH000056956,2019-02-08,Ground,100,106,61.43,2019-02-19,2019-02-15
30,30,DMH000056958,2019-02-08,Ground,83,113,78.15,2019-02-19,2019-02-15
31,31,DMH000056977,2019-02-08,Ground,80,79,49.38,2019-02-19,2019-02-15
32,32,DMH000056987,2019-02-08,Ground,8,8,20.28,2019-02-19,2019-02-15
33,33,DMH000059296,2019-03-15,Express,3,6,21.49,2019-03-20,2019-03-19
34,34,DMH000059298,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
35,35,DMH000059299,2019-03-15,Express,14,15,31.35,2019-03-20,2019-03-20
36,36,DMH000059301,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
37,37,DMH000059737,2019-03-22,Express,2,6,21.49,2019-03-27,2019-03-26
38,38,DMH000059739,2019-03-22,Express,4,6,21.49,2019-03-27,NaN
39,39,DMH000059798,2019-03-25,Express,9,9,21.81,2019-03-28,2019-04-01
40,40,DMH000059749,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
41,41,DMH000059750,2019-03-25,Express,1,6,24.81,2019-03-28,2019-03-28
42,42,DMH000059751,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
43,43,DMH000059753,2019-03-25,Express,7,8,23.63,2019-03-28,2019-04-01
44,44,DMH000067885,2019-08-02,Express,14,12,27.90,2019-08-07,2019-08-07
45,45,DMH000067886,2019-08-02,Express,13,11,26.72,2019-08-07,2019-08-07
46,46,DMH000067888,2019-08-02,Express,11,9,22.66,2019-08-07,2019-08-07
47,47,DMH000067908,2019-08-06,Ground,3,2,18.15,2019-08-14,2019-08-09
48,48,DMH000067909,2019-08-06,Express,114,110,159.57,2019-08-09,2019-08-09
49,49,DMH000067912,2019-08-06,Ground,10,11,18.54,2019-08-14,2019-08-14

In [13]:
sampleA.iloc[0,4]
sampleA.iloc[0,:]
sampleA.iloc[1:4,1:4]

              HWB    HWB Date Service Description
1    DMH000054437  2019-01-02             Express
2  DMH000054592R1  2019-01-04             Express
3    DMH000054593  2019-01-04              Ground

In [29]:
noACR1 = sampleA[~sampleA['HWB'].str.contains('R1') & 
                 ~sampleA['HWB'].str.contains('AC')]
noACR1.head(10)

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11
7,7,DMH000054704,2019-01-04,Express,8,9,24.89,2019-01-09,2019-01-09
8,8,DMH000054815,2019-01-07,Express,7,7,25.54,2019-01-11,2019-01-14
10,10,DMH000054825,2019-01-07,Express,7,7,22.23,2019-01-10,2019-01-12
12,12,DMH000054759,2019-01-07,Express,50,58,81.49,2019-01-10,2019-01-10
13,13,DMH000054762,2019-01-07,Ground,118,128,85.46,2019-01-15,2019-01-14

In [30]:
sampleA[sampleA['HWB'].str.contains('R1')]

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
9,9,DMH000054817R1,2019-01-07,Ground,8,8,17.03,2019-01-15,2019-01-14
11,11,DMH000054827R1,2019-01-07,Ground,7,8,19.94,2019-01-15,2019-01-14

In [142]:
s = pd.read_excel("Sample10 112819.xls")
s

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,weight,Cg Weight,Freight Charge,Total Revenue,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year
0,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,15.64,21.68,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
1,DMH000054436R1,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,10.00,10.00,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
2,DMH000054437,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,17.23,20.59,2019-01-07,2019-01-08,15:19:00,SONY - 9807237,A1512066,2019
3,DMH000054592,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,12.95,18.46,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
4,DMH000054592R1,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,5.00,5.00,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
5,DMH000054593,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,32,55,28.52,34.08,2019-01-14,2019-01-11,08:43:00,SONY - 9807237,A1514438,2019
6,DMH000054701,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,22.04,29.33,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
7,DMH000054701AC,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,3.00,3.00,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
8,DMH000054702,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,13,22.04,29.33,2019-01-09,2019-01-08,12:24:00,SONY - 9807237,A1514438,2019
9,DMH000054703,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,9,9,20.13,27.04,2019-01-09,2019-01-11,17:12:00,SONY - 9807237,A1514438,2019
10,DMH000054704,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,9,18.33,24.89,2019-01-09,2019-01-09,13:11:00,SONY - 9807237,A1514438,2019
11,DMH000054815,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,19.42,25.54,2019-01-11,2019-01-14,08:45:00,SONY - 9807237,A1514438,2019
12,DMH000054817,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,14.62,17.03,2019-01-15,2019-01-14,13:22:00,SONY - 9807237,A1514438,2019

In [128]:
s.groupby("HWB").sum()

,Orig zip,Shipper Ref,pieces,Product/Service,weight,Cg Weight,Freight Charge,Total Revenue,Year
HWB,,,,,,,,,
DMH000054436,90810,272420276671875,1,202,4,6,15.64,21.68,2019
DMH000054436R1,90810,272420276671875,1,202,4,6,10.00,10.00,2019
DMH000054437,90810,272420276671523,1,202,2,6,17.23,20.59,2019
DMH000054592,90810,272420276737625,1,202,3,3,12.95,18.46,2019
DMH000054592R1,90810,272420276737625,1,202,3,3,5.00,5.00,2019
DMH000054593,90810,272420276737588,3,260,32,55,28.52,34.08,2019
DMH000054701,90810,272420276828507,1,202,12,13,22.04,29.33,2019
DMH000054701AC,90810,272420276828507,1,202,12,13,3.00,3.00,2019
DMH000054702,90810,272420276737724,1,202,4,13,22.04,29.33,2019
DMH000054703,90810,272420276828705,1,202,9,9,20.13,27.04,2019
DMH000054704,90810,272420276828620,1,202,8,9,18.33,24.89,2019
DMH000054815,90810,272420276872241,1,202,7,7,19.42,25.54,2019
DMH000054817,90810,272420276900654,1,260,8,8,14.62,17.03,2019

In [77]:
s.loc["Total"] = s.sum()
s.iloc[11:,:]

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,weight,Cg Weight,Freight Charge,Total Revenue,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year
11,DMH000054815,2019-01-07 00:00:00,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,19.42,25.54,2019-01-11 00:00:00,2019-01-14 00:00:00,08:45:00,SONY - 9807237,A1514438,2019
12,DMH000054817,2019-01-07 00:00:00,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,14.62,17.03,2019-01-15 00:00:00,2019-01-14 00:00:00,13:22:00,SONY - 9807237,A1514438,2019
Total,DMH000054436DMH000054436R1DMH000054437DMH00005...,NaN,SONYSONYSONYSONYSONYSONYSONYSONYSONYSONYSONYSO...,2201 E CARSON ST2201 E CARSON ST2201 E CARSON ...,CARSONCARSONCARSONCARSONCARSONCARSONCARSONCARS...,CACACACACACACACACACACACACACACACACACACACACACACA...,14166360,3700 JERICHO RD3700 JERICHO RD3700 JERICHO RD3...,RICHMONDRICHMONDRICHMONDRICHMONDRICHMONDRICHMO...,BCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBCBC...,...,1296,1812,2507.04,3191.64,NaN,NaN,NaN,SONY - 9807237SONY - 9807237SONY - 9807237SONY...,A1512066A1512066A1512066A1514438A1514438A15144...,314964

In [152]:
s['HWB'].str.contains('R1')
s['HWB'][1].replace('R1', '')

for i in range(len(s)):
    print(s['HWB'][i])
    if s['HWB'].str.contains('R1'):
        pass

DMH000054436

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [145]:
s[s['HWB'].str.contains('R1')]
s[s['HWB'].str.contains('AC')]
s[~s['HWB'].str.contains('R1') & ~s['HWB'].str.contains('AC')]

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,weight,Cg Weight,Freight Charge,Total Revenue,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year
0,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,15.64,21.68,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
2,DMH000054437,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,17.23,20.59,2019-01-07,2019-01-08,15:19:00,SONY - 9807237,A1512066,2019
3,DMH000054592,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,12.95,18.46,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
5,DMH000054593,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,32,55,28.52,34.08,2019-01-14,2019-01-11,08:43:00,SONY - 9807237,A1514438,2019
6,DMH000054701,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,22.04,29.33,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
8,DMH000054702,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,13,22.04,29.33,2019-01-09,2019-01-08,12:24:00,SONY - 9807237,A1514438,2019
9,DMH000054703,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,9,9,20.13,27.04,2019-01-09,2019-01-11,17:12:00,SONY - 9807237,A1514438,2019
10,DMH000054704,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,9,18.33,24.89,2019-01-09,2019-01-09,13:11:00,SONY - 9807237,A1514438,2019
11,DMH000054815,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,19.42,25.54,2019-01-11,2019-01-14,08:45:00,SONY - 9807237,A1514438,2019
12,DMH000054817,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,14.62,17.03,2019-01-15,2019-01-14,13:22:00,SONY - 9807237,A1514438,2019

In [40]:
s.loc[s['HWB'].str.contains('R1'), 'weight'] #= 'ball sport'
s.loc[s['HWB'].str.contains('R1'), 'HWB']

1    DMH000054436R1
4    DMH000054592R1
Name: HWB, dtype: object

In [49]:
s['HWB'].str.contains('R1')

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
Name: HWB, dtype: bool

In [138]:
s

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,weight,Cg Weight,Freight Charge,Total Revenue,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year
0,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,15.64,21.68,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
1,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,6,10.00,10.00,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019
2,DMH000054437,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2,6,17.23,20.59,2019-01-07,2019-01-08,15:19:00,SONY - 9807237,A1512066,2019
3,DMH000054592,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,12.95,18.46,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
4,DMH000054592R1,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,3,3,5.00,5.00,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019
5,DMH000054593,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,32,55,28.52,34.08,2019-01-14,2019-01-11,08:43:00,SONY - 9807237,A1514438,2019
6,DMH000054701,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,22.04,29.33,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
7,DMH000054701AC,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,12,13,3.00,3.00,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019
8,DMH000054702,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,4,13,22.04,29.33,2019-01-09,2019-01-08,12:24:00,SONY - 9807237,A1514438,2019
9,DMH000054703,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,9,9,20.13,27.04,2019-01-09,2019-01-11,17:12:00,SONY - 9807237,A1514438,2019
10,DMH000054704,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,9,18.33,24.89,2019-01-09,2019-01-09,13:11:00,SONY - 9807237,A1514438,2019
11,DMH000054815,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,7,7,19.42,25.54,2019-01-11,2019-01-14,08:45:00,SONY - 9807237,A1514438,2019
12,DMH000054817,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,8,8,14.62,17.03,2019-01-15,2019-01-14,13:22:00,SONY - 9807237,A1514438,2019

In [139]:
for i in range(len(s)):
    print(s["HWB"][i])

DMH000054436
DMH000054436
DMH000054437
DMH000054592
DMH000054592R1
DMH000054593
DMH000054701
DMH000054701AC
DMH000054702
DMH000054703
DMH000054704
DMH000054815
DMH000054817

In [136]:
range(len(s))

range(0, 13)

In [59]:
s['HWB'][1].replace('R1', '')

'DMH000054436'

In [95]:
s['HWB'].str.contains('R1')
ft = s[s['HWB'].str.contains('R1')][["Freight Charge","Total Revenue"]]
ft

       Freight Charge  Total Revenue
1               10.00          10.00
4                5.00           5.00
Total         2507.04        3191.64

In [111]:
s[s['HWB'] == s['HWB'][1].replace('R1', '')]
s[s['HWB'] == s['HWB'][1].replace('R1', '')][["Freight Charge","Total Revenue"]]

   Freight Charge  Total Revenue
0           15.64          21.68

In [132]:
s['HWB'][1] = s['HWB'][1].replace('R1', '')
s['HWB'][:2]

C:\Users\ankur\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

0    DMH000054436
1    DMH000054436
Name: HWB, dtype: object

In [153]:
s.groupby("HWB")["Freight Charge"].sum()

HWB
DMH000054436      15.64
DMH000054436R1    10.00
DMH000054437      17.23
DMH000054592      12.95
DMH000054592R1     5.00
DMH000054593      28.52
DMH000054701      22.04
DMH000054701AC     3.00
DMH000054702      22.04
DMH000054703      20.13
DMH000054704      18.33
DMH000054815      19.42
DMH000054817      14.62
Name: Freight Charge, dtype: float64

In [106]:
ft.loc[1]

Freight Charge    10.0
Total Revenue     10.0
Name: 1, dtype: float64

In [90]:
s[s['HWB'].str.contains('R1')]["HWB"]

1                                           DMH000054436R1
4                                           DMH000054592R1
Total    DMH000054436DMH000054436R1DMH000054437DMH00005...
Name: HWB, dtype: object

In [19]:
noACR1.loc["Total"] = noACR1.sum()
noACR1

C:\Users\ankur\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11
7,7,DMH000054704,2019-01-04,Express,8,9,24.89,2019-01-09,2019-01-09
8,8,DMH000054815,2019-01-07,Express,7,7,25.54,2019-01-11,2019-01-14
10,10,DMH000054825,2019-01-07,Express,7,7,22.23,2019-01-10,2019-01-12
12,12,DMH000054759,2019-01-07,Express,50,58,81.49,2019-01-10,2019-01-10
13,13,DMH000054762,2019-01-07,Ground,118,128,85.46,2019-01-15,2019-01-14
14,14,DMH000054889,2019-01-08,Express,7,8,23.23,2019-01-11,2019-01-11
15,15,DMH000054892,2019-01-08,Express,10,10,25.32,2019-01-11,2019-01-17
17,17,DMH000055002,2019-01-09,Ground,85,85,43.99,2019-01-17,2019-01-15
18,18,DMH000057262,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
20,20,DMH000057266,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-21
21,21,DMH000057267,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-15
23,23,DMH000057153,2019-02-08,Ground,18,18,20.34,2019-02-19,2019-02-15
24,24,DMH000057155,2019-02-08,Ground,2,2,17.39,2019-02-18,2019-02-15
25,25,DMH000057156,2019-02-08,Ground,161,170,92.26,2019-02-19,2019-02-15
26,26,DMH000057166,2019-02-08,Express,42,43,62.92,2019-02-13,2019-02-13
27,27,DMH000057169,2019-02-08,Express,57,58,83.22,2019-02-13,2019-02-13
28,28,DMH000057170,2019-02-08,Express,23,24,38.84,2019-02-13,2019-02-12
29,29,DMH000056956,2019-02-08,Ground,100,106,61.43,2019-02-19,2019-02-15
30,30,DMH000056958,2019-02-08,Ground,83,113,78.15,2019-02-19,2019-02-15
31,31,DMH000056977,2019-02-08,Ground,80,79,49.38,2019-02-19,2019-02-15
32,32,DMH000056987,2019-02-08,Ground,8,8,20.28,2019-02-19,2019-02-15
33,33,DMH000059296,2019-03-15,Express,3,6,21.49,2019-03-20,2019-03-19
34,34,DMH000059298,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
35,35,DMH000059299,2019-03-15,Express,14,15,31.35,2019-03-20,2019-03-20
36,36,DMH000059301,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
37,37,DMH000059737,2019-03-22,Express,2,6,21.49,2019-03-27,2019-03-26
38,38,DMH000059739,2019-03-22,Express,4,6,21.49,2019-03-27,NaN
39,39,DMH000059798,2019-03-25,Express,9,9,21.81,2019-03-28,2019-04-01
40,40,DMH000059749,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
41,41,DMH000059750,2019-03-25,Express,1,6,24.81,2019-03-28,2019-03-28
42,42,DMH000059751,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
43,43,DMH000059753,2019-03-25,Express,7,8,23.63,2019-03-28,2019-04-01
44,44,DMH000067885,2019-08-02,Express,14,12,27.90,2019-08-07,2019-08-07
45,45,DMH000067886,2019-08-02,Express,13,11,26.72,2019-08-07,2019-08-07
46,46,DMH000067888,2019-08-02,Express,11,9,22.66,2019-08-07,2019-08-07
47,47,DMH000067908,2019-08-06,Ground,3,2,18.15,2019-08-14,2019-08-09
48,48,DMH000067909,2019-08-06,Express,114,110,159.57,2019-08-09,2019-08-09
49,49,DMH000067912,2019-08-06,Ground,10,11,18.54,2019-08-14,2019-08-14
Total,1141,DMH000054436DMH000054437DMH000054593DMH0000547...,2019-01-022019-01-022019-01-042019-01-042019-0...,ExpressExpressGroundExpressExpressExpressExpre...,1201,1314,1605.70,2019-01-072019-01-072019-01-142019-01-092019-0...,NaN

In [22]:
sampleA

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
5,5,DMH000054702AC,2019-01-04,Express,4,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11
7,7,DMH000054704,2019-01-04,Express,8,9,24.89,2019-01-09,2019-01-09
8,8,DMH000054815,2019-01-07,Express,7,7,25.54,2019-01-11,2019-01-14
9,9,DMH000054817R1,2019-01-07,Ground,8,8,17.03,2019-01-15,2019-01-14
10,10,DMH000054825,2019-01-07,Express,7,7,22.23,2019-01-10,2019-01-12
11,11,DMH000054827R1,2019-01-07,Ground,7,8,19.94,2019-01-15,2019-01-14
12,12,DMH000054759,2019-01-07,Express,50,58,81.49,2019-01-10,2019-01-10
13,13,DMH000054762,2019-01-07,Ground,118,128,85.46,2019-01-15,2019-01-14
14,14,DMH000054889,2019-01-08,Express,7,8,23.23,2019-01-11,2019-01-11
15,15,DMH000054892,2019-01-08,Express,10,10,25.32,2019-01-11,2019-01-17
16,16,DMH000055001AC,2019-01-09,Express,8,9,26.36,2019-01-14,2019-01-14
17,17,DMH000055002,2019-01-09,Ground,85,85,43.99,2019-01-17,2019-01-15
18,18,DMH000057262,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
19,19,DMH000057265AC,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-12
20,20,DMH000057266,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-21
21,21,DMH000057267,2019-02-08,Express,20,21,38.32,2019-02-13,2019-02-15
22,22,DMH000057269AC,2019-02-08,Express,7,7,22.61,2019-02-13,2019-02-14
23,23,DMH000057153,2019-02-08,Ground,18,18,20.34,2019-02-19,2019-02-15
24,24,DMH000057155,2019-02-08,Ground,2,2,17.39,2019-02-18,2019-02-15
25,25,DMH000057156,2019-02-08,Ground,161,170,92.26,2019-02-19,2019-02-15
26,26,DMH000057166,2019-02-08,Express,42,43,62.92,2019-02-13,2019-02-13
27,27,DMH000057169,2019-02-08,Express,57,58,83.22,2019-02-13,2019-02-13
28,28,DMH000057170,2019-02-08,Express,23,24,38.84,2019-02-13,2019-02-12
29,29,DMH000056956,2019-02-08,Ground,100,106,61.43,2019-02-19,2019-02-15
30,30,DMH000056958,2019-02-08,Ground,83,113,78.15,2019-02-19,2019-02-15
31,31,DMH000056977,2019-02-08,Ground,80,79,49.38,2019-02-19,2019-02-15
32,32,DMH000056987,2019-02-08,Ground,8,8,20.28,2019-02-19,2019-02-15
33,33,DMH000059296,2019-03-15,Express,3,6,21.49,2019-03-20,2019-03-19
34,34,DMH000059298,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
35,35,DMH000059299,2019-03-15,Express,14,15,31.35,2019-03-20,2019-03-20
36,36,DMH000059301,2019-03-15,Ground,10,10,17.39,2019-03-25,2019-03-22
37,37,DMH000059737,2019-03-22,Express,2,6,21.49,2019-03-27,2019-03-26
38,38,DMH000059739,2019-03-22,Express,4,6,21.49,2019-03-27,NaN
39,39,DMH000059798,2019-03-25,Express,9,9,21.81,2019-03-28,2019-04-01
40,40,DMH000059749,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
41,41,DMH000059750,2019-03-25,Express,1,6,24.81,2019-03-28,2019-03-28
42,42,DMH000059751,2019-03-25,Express,2,6,21.49,2019-03-28,2019-03-28
43,43,DMH000059753,2019-03-25,Express,7,8,23.63,2019-03-28,2019-04-01
44,44,DMH000067885,2019-08-02,Express,14,12,27.90,2019-08-07,2019-08-07
45,45,DMH000067886,2019-08-02,Express,13,11,26.72,2019-08-07,2019-08-07
46,46,DMH000067888,2019-08-02,Express,11,9,22.66,2019-08-07,2019-08-07
47,47,DMH000067908,2019-08-06,Ground,3,2,18.15,2019-08-14,2019-08-09
48,48,DMH000067909,2019-08-06,Express,114,110,159.57,2019-08-09,2019-08-09
49,49,DMH000067912,2019-08-06,Ground,10,11,18.54,2019-08-14,2019-08-14

In [ ]:
s

In [106]:
len(noACR1)
# len(sampleA)

43

In [112]:
print(df11.head())
print(df12.head())
df1112 = pd.merge(df11, df12,  how="outer")
df1112

            HWB   HWB Date Orig City  Orig zip Shipper State
0  DMH000054436 2019-01-02    CARSON     90810            BC
1  DMH000054437 2019-01-02    CARSON     90810            BC
2  DMH000054592 2019-01-04    CARSON     90810            BC
3  DMH000054593 2019-01-04    CARSON     90810            BC
4  DMH000054701 2019-01-04    CARSON     90810            BC
            HWB  weight  Cg Weight  Freight Charge  Total Revenue
0  DMH000054436       4          6           15.64          21.68
1  DMH000054437       2          6           17.23          20.59
2  DMH000054592       3          3           12.95          18.46
3  DMH000054593      32         55           28.52          34.08
4  DMH000054701      12         13           22.04          29.33

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Cg Weight,Freight Charge,Total Revenue
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,6,15.64,21.68
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,6,17.23,20.59
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,3,12.95,18.46
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,55,28.52,34.08
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,13,22.04,29.33
5,DMH000054702,2019-01-04,CARSON,90810,BC,4,13,22.04,29.33
6,DMH000054703,2019-01-04,CARSON,90810,BC,9,9,20.13,27.04
7,DMH000054704,2019-01-04,CARSON,90810,BC,8,9,18.33,24.89
8,DMH000054815,2019-01-07,CARSON,90810,BC,7,7,19.42,25.54
9,DMH000054817,2019-01-07,CARSON,90810,BC,8,8,14.62,17.03
10,DMH000054825,2019-01-07,CARSON,90810,BC,7,7,16.58,22.23
11,DMH000054827,2019-01-07,CARSON,90810,BC,7,8,14.62,19.94
12,DMH000054759,2019-01-07,CARSON,90810,BC,50,58,69.95,81.49
13,DMH000054762,2019-01-07,CARSON,90810,BC,118,128,51.02,85.46
14,DMH000054889,2019-01-08,CARSON,90810,BC,7,8,17.44,23.23
15,DMH000054892,2019-01-08,CARSON,90810,BC,10,10,19.23,25.32
16,DMH000055001,2019-01-09,CARSON,90810,BC,8,9,20.13,26.36
17,DMH000055002,2019-01-09,CARSON,90810,BC,85,85,37.76,43.99
18,DMH000057262,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
19,DMH000057265,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
20,DMH000057266,2019-02-08,CARSON,90810,BC,20,21,30.68,38.32
21,DMH000057267,2019-02-08,CARSON,90810,BC,20,21,30.68,38.32
22,DMH000057269,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
23,DMH000057153,2019-02-08,CARSON,90810,BC,18,18,17.61,20.34
24,DMH000057155,2019-02-08,CARSON,90810,BC,2,2,15.06,17.39
25,DMH000057156,2019-02-08,CARSON,90810,BC,161,170,66.14,92.26
26,DMH000057166,2019-02-08,CARSON,90810,BC,42,43,54.48,62.92
27,DMH000057169,2019-02-08,CARSON,90810,BC,57,58,72.05,83.22
28,DMH000057170,2019-02-08,CARSON,90810,BC,23,24,33.63,38.84
29,DMH000056956,2019-02-08,CARSON,90810,BC,100,106,46.02,61.43
30,DMH000056958,2019-02-08,CARSON,90810,BC,83,113,47.80,78.15
31,DMH000056977,2019-02-08,CARSON,90810,BC,80,79,36.99,49.38
32,DMH000056987,2019-02-08,CARSON,90810,BC,8,8,15.06,20.28
33,DMH000059296,2019-03-15,CARSON,90810,BC,3,6,16.11,21.49
34,DMH000059298,2019-03-15,CARSON,90810,BC,10,10,15.06,17.39
35,DMH000059299,2019-03-15,CARSON,90810,BC,14,15,24.64,31.35
36,DMH000059301,2019-03-15,CARSON,90810,BC,10,10,15.06,17.39
37,DMH000059737,2019-03-22,CARSON,90810,BC,2,6,16.11,21.49
38,DMH000059739,2019-03-22,CARSON,90810,BC,4,6,16.11,21.49
39,DMH000059798,2019-03-25,CARSON,90810,BC,9,9,18.88,21.81
40,DMH000059749,2019-03-25,CARSON,90810,BC,2,6,16.11,21.49
41,DMH000059750,2019-03-25,CARSON,90810,BC,1,6,18.98,24.81
42,DMH000059751,2019-03-25,CARSON,90810,BC,2,6,16.11,21.49
43,DMH000059753,2019-03-25,CARSON,90810,BC,7,8,17.96,23.63
44,DMH000067885,2019-08-02,CARSON,90810,BC,14,12,21.76,27.90
45,DMH000067886,2019-08-02,CARSON,90810,BC,13,11,20.78,26.72
46,DMH000067888,2019-08-02,CARSON,90810,BC,11,9,18.88,22.66
47,DMH000067908,2019-08-06,CARSON,90810,BC,3,2,15.06,18.15
48,DMH000067909,2019-08-06,CARSON,90810,BC,114,110,132.42,159.57
49,DMH000067912,2019-08-06,CARSON,90810,BC,10,11,15.39,18.54

In [41]:
pd.merge_ordered(df1, df12, on='HWB', suffixes=['_1', '_2'], fill_method='ffill')

,HWB,HWB Date,Shipper Name,Orig Address1,Orig City,Orig State,Orig zip,Shipper Address1,Shipper City,Shipper State,...,Due Date,POD Date,POD Time,Family Name,Master Invoice Number,Year,weight_2,Cg Weight_2,Freight Charge_2,Total Revenue_2
0,DMH000054436,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-07,2019-01-08,10:55:00,SONY - 9807237,A1512066,2019,4,6,15.64,21.68
1,DMH000054437,2019-01-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-07,2019-01-08,15:19:00,SONY - 9807237,A1512066,2019,2,6,17.23,20.59
2,DMH000054592,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-09,2019-01-08,17:39:00,SONY - 9807237,A1514438,2019,3,3,12.95,18.46
3,DMH000054593,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-14,2019-01-11,08:43:00,SONY - 9807237,A1514438,2019,32,55,28.52,34.08
4,DMH000054701,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-09,2019-01-08,13:38:00,SONY - 9807237,A1514438,2019,12,13,22.04,29.33
5,DMH000054702,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-09,2019-01-08,12:24:00,SONY - 9807237,A1514438,2019,4,13,22.04,29.33
6,DMH000054703,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-09,2019-01-11,17:12:00,SONY - 9807237,A1514438,2019,9,9,20.13,27.04
7,DMH000054704,2019-01-04,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-09,2019-01-09,13:11:00,SONY - 9807237,A1514438,2019,8,9,18.33,24.89
8,DMH000054759,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-10,2019-01-10,10:29:00,SONY - 9807237,A1514438,2019,50,58,69.95,81.49
9,DMH000054762,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-15,2019-01-14,09:24:00,SONY - 9807237,A1514438,2019,118,128,51.02,85.46
10,DMH000054815,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-11,2019-01-14,08:45:00,SONY - 9807237,A1514438,2019,7,7,19.42,25.54
11,DMH000054817,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-15,2019-01-14,13:22:00,SONY - 9807237,A1514438,2019,8,8,14.62,17.03
12,DMH000054825,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-10,2019-01-12,11:24:00,SONY - 9807237,A1514438,2019,7,7,16.58,22.23
13,DMH000054827,2019-01-07,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-15,2019-01-14,10:29:00,SONY - 9807237,A1514438,2019,7,8,14.62,19.94
14,DMH000054889,2019-01-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-11,2019-01-11,15:34:00,SONY - 9807237,A1514438,2019,7,8,17.44,23.23
15,DMH000054892,2019-01-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-11,2019-01-17,10:22:00,SONY - 9807237,A1514438,2019,10,10,19.23,25.32
16,DMH000055001,2019-01-09,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-14,2019-01-14,14:44:00,SONY - 9807237,A1514438,2019,8,9,20.13,26.36
17,DMH000055002,2019-01-09,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-01-17,2019-01-15,10:58:00,SONY - 9807237,A1514438,2019,85,85,37.76,43.99
18,DMH000056956,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,08:34:00,SONY - 9807237,A1518983,2019,100,106,46.02,61.43
19,DMH000056958,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,09:28:00,SONY - 9807237,A1518983,2019,83,113,47.80,78.15
20,DMH000056977,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,13:05:00,SONY - 9807237,A1518983,2019,80,79,36.99,49.38
21,DMH000056987,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,11:48:00,SONY - 9807237,A1518983,2019,8,8,15.06,20.28
22,DMH000057153,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,10:10:00,SONY - 9807237,A1518983,2019,18,18,17.61,20.34
23,DMH000057155,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-18,2019-02-15,11:44:00,SONY - 9807237,A1518983,2019,2,2,15.06,17.39
24,DMH000057156,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-19,2019-02-15,11:56:00,SONY - 9807237,A1518983,2019,161,170,66.14,92.26
25,DMH000057166,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-13,08:25:00,SONY - 9807237,A1518983,2019,42,43,54.48,62.92
26,DMH000057169,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-13,08:58:00,SONY - 9807237,A1518983,2019,57,58,72.05,83.22
27,DMH000057170,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-12,10:12:00,SONY - 9807237,A1518983,2019,23,24,33.63,38.84
28,DMH000057262,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-14,11:37:00,SONY - 9807237,A1518983,2019,7,7,17.08,22.61
29,DMH000057265,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-12,13:07:00,SONY - 9807237,A1518983,2019,7,7,17.08,22.61
30,DMH000057266,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-21,20:50:00,SONY - 9807237,A1518983,2019,20,21,30.68,38.32
31,DMH000057267,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-15,13:43:00,SONY - 9807237,A1518983,2019,20,21,30.68,38.32
32,DMH000057269,2019-02-08,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-02-13,2019-02-14,13:49:00,SONY - 9807237,A1518983,2019,7,7,17.08,22.61
33,DMH000059296,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-20,2019-03-19,11:49:00,SONY - 9807237,A1524874,2019,3,6,16.11,21.49
34,DMH000059298,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-25,2019-03-22,08:32:00,SONY - 9807237,A1524874,2019,10,10,15.06,17.39
35,DMH000059299,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-20,2019-03-20,08:57:00,SONY - 9807237,A1524874,2019,14,15,24.64,31.35
36,DMH000059301,2019-03-15,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-25,2019-03-22,09:00:00,SONY - 9807237,A1524874,2019,10,10,15.06,17.39
37,DMH000059737,2019-03-22,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-27,2019-03-26,13:23:00,SONY - 9807237,A1525978,2019,2,6,16.11,21.49
38,DMH000059739,2019-03-22,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-27,NaT,NaN,SONY - 9807237,A1525978,2019,4,6,16.11,21.49
39,DMH000059749,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-28,2019-03-28,14:51:00,SONY - 9807237,A1525978,2019,2,6,16.11,21.49
40,DMH000059750,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-28,2019-03-28,16:20:00,SONY - 9807237,A1525978,2019,1,6,18.98,24.81
41,DMH000059751,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-28,2019-03-28,14:51:00,SONY - 9807237,A1525978,2019,2,6,16.11,21.49
42,DMH000059753,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-28,2019-04-01,17:35:00,SONY - 9807237,A1525978,2019,7,8,17.96,23.63
43,DMH000059798,2019-03-25,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-03-28,2019-04-01,14:47:00,SONY - 9807237,A1525978,2019,9,9,18.88,21.81
44,DMH000067885,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-07,2019-08-07,11:38:00,SONY - 9807237,A1547385,2019,14,12,21.76,27.90
45,DMH000067886,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-07,2019-08-07,12:14:00,SONY - 9807237,A1547385,2019,13,11,20.78,26.72
46,DMH000067888,2019-08-02,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-07,2019-08-07,13:33:00,SONY - 9807237,A1547385,2019,11,9,18.88,22.66
47,DMH000067908,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-14,2019-08-09,12:31:00,SONY - 9807237,A1547385,2019,3,2,15.06,18.15
48,DMH000067909,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-09,2019-08-09,11:48:00,SONY - 9807237,A1547385,2019,114,110,132.42,159.57
49,DMH000067912,2019-08-06,SONY,2201 E CARSON ST,CARSON,CA,90810,3700 JERICHO RD,RICHMOND,BC,...,2019-08-14,2019-08-14,08:26:00,SONY - 9807237,A1547385,2019,10,11,15.39,18.54

In [44]:
df1112.to_csv("1112.csv")

In [45]:
open("1112.csv")

In [18]:
class Snake:
    name = "python"
    def change_name(self, new_name): # note that the first argument is self
        self.name = new_name # access the class attribute with the self keyword

In [6]:
Snake.name

'python'

In [9]:
snake = Snake()
print(snake.name)
snake.change_name("anaconda")
print(snake.name)

python
anaconda

In [25]:
df11.head()

            HWB   HWB Date Orig City  Orig zip Shipper State
0  DMH000054436 2019-01-02    CARSON     90810            BC
1  DMH000054437 2019-01-02    CARSON     90810            BC
2  DMH000054592 2019-01-04    CARSON     90810            BC
3  DMH000054593 2019-01-04    CARSON     90810            BC
4  DMH000054701 2019-01-04    CARSON     90810            BC

In [26]:
df12.head()

            HWB  weight  Cg Weight  Freight Charge  Total Revenue
0  DMH000054436       4          6           15.64          21.68
1  DMH000054437       2          6           17.23          20.59
2  DMH000054592       3          3           12.95          18.46
3  DMH000054593      32         55           28.52          34.08
4  DMH000054701      12         13           22.04          29.33

In [27]:
pd.merge(df11, df12).head()

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Cg Weight,Freight Charge,Total Revenue
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,6,15.64,21.68
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,6,17.23,20.59
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,3,12.95,18.46
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,55,28.52,34.08
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,13,22.04,29.33

In [28]:
df111 = df1[["HWB", "HWB Date", "Orig City", "Orig zip", "Shipper State", "weight", "Total Revenue"]]
df111.head()

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Total Revenue
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,21.68
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,20.59
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,18.46
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,34.08
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,29.33

In [29]:
pd.merge(df111, df12).head()

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Total Revenue,Cg Weight,Freight Charge
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,21.68,6,15.64
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,20.59,6,17.23
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,18.46,3,12.95
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,34.08,55,28.52
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,29.33,13,22.04

In [33]:
pd.merge(df111, df12).sort_values("Total Revenue").head()

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Total Revenue,Cg Weight,Freight Charge
9,DMH000054817,2019-01-07,CARSON,90810,BC,8,17.03,8,14.62
24,DMH000057155,2019-02-08,CARSON,90810,BC,2,17.39,2,15.06
36,DMH000059301,2019-03-15,CARSON,90810,BC,10,17.39,10,15.06
34,DMH000059298,2019-03-15,CARSON,90810,BC,10,17.39,10,15.06
47,DMH000067908,2019-08-06,CARSON,90810,BC,3,18.15,2,15.06

In [36]:
 pd.merge_ordered(df11, df12)

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Cg Weight,Freight Charge,Total Revenue
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,6,15.64,21.68
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,6,17.23,20.59
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,3,12.95,18.46
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,55,28.52,34.08
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,13,22.04,29.33
5,DMH000054702,2019-01-04,CARSON,90810,BC,4,13,22.04,29.33
6,DMH000054703,2019-01-04,CARSON,90810,BC,9,9,20.13,27.04
7,DMH000054704,2019-01-04,CARSON,90810,BC,8,9,18.33,24.89
8,DMH000054759,2019-01-07,CARSON,90810,BC,50,58,69.95,81.49
9,DMH000054762,2019-01-07,CARSON,90810,BC,118,128,51.02,85.46
10,DMH000054815,2019-01-07,CARSON,90810,BC,7,7,19.42,25.54
11,DMH000054817,2019-01-07,CARSON,90810,BC,8,8,14.62,17.03
12,DMH000054825,2019-01-07,CARSON,90810,BC,7,7,16.58,22.23
13,DMH000054827,2019-01-07,CARSON,90810,BC,7,8,14.62,19.94
14,DMH000054889,2019-01-08,CARSON,90810,BC,7,8,17.44,23.23
15,DMH000054892,2019-01-08,CARSON,90810,BC,10,10,19.23,25.32
16,DMH000055001,2019-01-09,CARSON,90810,BC,8,9,20.13,26.36
17,DMH000055002,2019-01-09,CARSON,90810,BC,85,85,37.76,43.99
18,DMH000056956,2019-02-08,CARSON,90810,BC,100,106,46.02,61.43
19,DMH000056958,2019-02-08,CARSON,90810,BC,83,113,47.80,78.15
20,DMH000056977,2019-02-08,CARSON,90810,BC,80,79,36.99,49.38
21,DMH000056987,2019-02-08,CARSON,90810,BC,8,8,15.06,20.28
22,DMH000057153,2019-02-08,CARSON,90810,BC,18,18,17.61,20.34
23,DMH000057155,2019-02-08,CARSON,90810,BC,2,2,15.06,17.39
24,DMH000057156,2019-02-08,CARSON,90810,BC,161,170,66.14,92.26
25,DMH000057166,2019-02-08,CARSON,90810,BC,42,43,54.48,62.92
26,DMH000057169,2019-02-08,CARSON,90810,BC,57,58,72.05,83.22
27,DMH000057170,2019-02-08,CARSON,90810,BC,23,24,33.63,38.84
28,DMH000057262,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
29,DMH000057265,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
30,DMH000057266,2019-02-08,CARSON,90810,BC,20,21,30.68,38.32
31,DMH000057267,2019-02-08,CARSON,90810,BC,20,21,30.68,38.32
32,DMH000057269,2019-02-08,CARSON,90810,BC,7,7,17.08,22.61
33,DMH000059296,2019-03-15,CARSON,90810,BC,3,6,16.11,21.49
34,DMH000059298,2019-03-15,CARSON,90810,BC,10,10,15.06,17.39
35,DMH000059299,2019-03-15,CARSON,90810,BC,14,15,24.64,31.35
36,DMH000059301,2019-03-15,CARSON,90810,BC,10,10,15.06,17.39
37,DMH000059737,2019-03-22,CARSON,90810,BC,2,6,16.11,21.49
38,DMH000059739,2019-03-22,CARSON,90810,BC,4,6,16.11,21.49
39,DMH000059749,2019-03-25,CARSON,90810,BC,2,6,16.11,21.49
40,DMH000059750,2019-03-25,CARSON,90810,BC,1,6,18.98,24.81
41,DMH000059751,2019-03-25,CARSON,90810,BC,2,6,16.11,21.49
42,DMH000059753,2019-03-25,CARSON,90810,BC,7,8,17.96,23.63
43,DMH000059798,2019-03-25,CARSON,90810,BC,9,9,18.88,21.81
44,DMH000067885,2019-08-02,CARSON,90810,BC,14,12,21.76,27.90
45,DMH000067886,2019-08-02,CARSON,90810,BC,13,11,20.78,26.72
46,DMH000067888,2019-08-02,CARSON,90810,BC,11,9,18.88,22.66
47,DMH000067908,2019-08-06,CARSON,90810,BC,3,2,15.06,18.15
48,DMH000067909,2019-08-06,CARSON,90810,BC,114,110,132.42,159.57
49,DMH000067912,2019-08-06,CARSON,90810,BC,10,11,15.39,18.54

In [44]:
pd.merge_ordered(df111, df12, on=['HWB', 'weight'], suffixes=['_df11', '_df12']).head()

,HWB,HWB Date,Orig City,Orig zip,Shipper State,weight,Total Revenue_df11,Cg Weight,Freight Charge,Total Revenue_df12
0,DMH000054436,2019-01-02,CARSON,90810,BC,4,21.68,6,15.64,21.68
1,DMH000054437,2019-01-02,CARSON,90810,BC,2,20.59,6,17.23,20.59
2,DMH000054592,2019-01-04,CARSON,90810,BC,3,18.46,3,12.95,18.46
3,DMH000054593,2019-01-04,CARSON,90810,BC,32,34.08,55,28.52,34.08
4,DMH000054701,2019-01-04,CARSON,90810,BC,12,29.33,13,22.04,29.33

In [47]:
labels, uniques = pd.factorize(df["Master Invoice Number"]) 
  
print("Numeric Representation : \n", labels) 
print("Unique Values : \n", uniques)

Numeric Representation :
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3
 4 4 4 4 4 4 4 5 5 5 5 5 5]
Unique Values :
 Index(['A1512066', 'A1514438', 'A1518983', 'A1524874', 'A1525978', 'A1547385'], dtype='object')

In [48]:
df["Master Invoice Number"]

0     A1512066
1     A1512066
2     A1514438
3     A1514438
4     A1514438
5     A1514438
6     A1514438
7     A1514438
8     A1514438
9     A1514438
10    A1514438
11    A1514438
12    A1514438
13    A1514438
14    A1514438
15    A1514438
16    A1514438
17    A1514438
18    A1518983
19    A1518983
20    A1518983
21    A1518983
22    A1518983
23    A1518983
24    A1518983
25    A1518983
26    A1518983
27    A1518983
28    A1518983
29    A1518983
30    A1518983
31    A1518983
32    A1518983
33    A1524874
34    A1524874
35    A1524874
36    A1524874
37    A1525978
38    A1525978
39    A1525978
40    A1525978
41    A1525978
42    A1525978
43    A1525978
44    A1547385
45    A1547385
46    A1547385
47    A1547385
48    A1547385
49    A1547385
Name: Master Invoice Number, dtype: object

In [118]:
L, U = pd.factorize(df["HWB Date"]) 
  
print("Labels : \n", L) 
print("\n\nUniques : \n", U)

Labels :
 [ 0  0  1  1  1  1  1  1  2  2  2  2  2  2  3  3  4  4  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  6  6  6  6  7  7  8  8  8  8  8  9  9  9 10
 10 10]


Uniques :
 DatetimeIndex(['2019-01-02', '2019-01-04', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-02-08', '2019-03-15', '2019-03-22',
               '2019-03-25', '2019-08-02', '2019-08-06'],
              dtype='datetime64[ns]', freq=None)

In [140]:
# for i in range(len(sampleA)):
#     print(sampleA["HWB"][i])
# # len(sampleA)
for i,j in enumerate(sampleA["HWB"]):
    print("\n", i)
    print("\n", j)

 0

 DMH000054436

 1

 DMH000054437

 2

 DMH000054592R1

 3

 DMH000054593

 4

 DMH000054701

 5

 DMH000054702AC

 6

 DMH000054703

 7

 DMH000054704

 8

 DMH000054815

 9

 DMH000054817R1

 10

 DMH000054825

 11

 DMH000054827R1

 12

 DMH000054759

 13

 DMH000054762

 14

 DMH000054889

 15

 DMH000054892

 16

 DMH000055001AC

 17

 DMH000055002

 18

 DMH000057262

 19

 DMH000057265AC

 20

 DMH000057266

 21

 DMH000057267

 22

 DMH000057269AC

 23

 DMH000057153

 24

 DMH000057155

 25

 DMH000057156

 26

 DMH000057166

 27

 DMH000057169

 28

 DMH000057170

 29

 DMH000056956

 30

 DMH000056958

 31

 DMH000056977

 32

 DMH000056987

 33

 DMH000059296

 34

 DMH000059298

 35

 DMH000059299

 36

 DMH000059301

 37

 DMH000059737

 38

 DMH000059739

 39

 DMH000059798

 40

 DMH000059749

 41

 DMH000059750

 42

 DMH000059751

 43

 DMH000059753

 44

 DMH000067885

 45

 DMH000067886

 46

 DMH000067888

 47

 DMH000067908

 48

 DMH000067909

 49

 DMH000067912

In [150]:
sampleA.head()

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
2,2,DMH000054592R1,2019-01-04,Express,3,3,18.46,2019-01-09,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08

In [151]:
noR1AC.head()

,Unnamed: 0,HWB,HWB Date,Service Description,weight,Cg Weight,Total Revenue,Due Date,POD Date
0,0,DMH000054436,2019-01-02,Express,4,6,21.68,2019-01-07,2019-01-08
1,1,DMH000054437,2019-01-02,Express,2,6,20.59,2019-01-07,2019-01-08
3,3,DMH000054593,2019-01-04,Ground,32,55,34.08,2019-01-14,2019-01-11
4,4,DMH000054701,2019-01-04,Express,12,13,29.33,2019-01-09,2019-01-08
6,6,DMH000054703,2019-01-04,Express,9,9,27.04,2019-01-09,2019-01-11

In [162]:
noR1AC.sum(axis=0)
print(noR1AC[["Cg Weight","Total Revenue"]].sum(axis=0))
print("\n\nHWB count:", noR1AC.HWB.count())

Cg Weight        1314.0
Total Revenue    1605.7
dtype: float64


HWB count: 43

In [ ]:
date_time_str = '2018-06-29 08:15:27.243860'
date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S.%f')

print('Date:', date_time_obj.date())
print('Time:', date_time_obj.time())
print('Date-time:', date_time_obj)

In [172]:
sampleA["POD Date"] > sampleA["Due Date"]
# sampleA.loc[sampleA["POD Date"] > sampleA["Due Date"]]

0      True
1      True
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18     True
19    False
20     True
21     True
22     True
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39     True
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [173]:
import smtplib

def prompt(prompt):
    return input(prompt).strip()

fromaddr = prompt("From: ")
toaddrs  = prompt("To: ").split()
print("Enter message, end with ^D (Unix) or ^Z (Windows):")

# Add the From: and To: headers at the start!
msg = ("From: %s\r\nTo: %s\r\n\r\n"
       % (fromaddr, ", ".join(toaddrs)))
while True:
    try:
        line = input()
    except EOFError:
        break
    if not line:
        break
    msg = msg + line

print("Message length is", len(msg))

server = smtplib.SMTP('localhost')
server.set_debuglevel(1)
server.sendmail(fromaddr, toaddrs, msg)
server.quit()

From: p.ankur.715@gmail.com
To: raluca222@yahoo.com
Enter message, end with ^D (Unix) or ^Z (Windows):
Hi Raluca! Remember, Python FTW!! :)
^Z

Message length is 94

OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions